//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikaDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Дети
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Дети()
        {
            this.Заявления = new HashSet<Заявления>();
        }
    
        public int Код { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public int ПолКод { get; set; }
        public System.DateTime ДатаРождения { get; set; } = DateTime.Now;
        public int ВозрастКод { get; set; }
        public int РегионКод { get; set; }
        public int ГородКод { get; set; }
        public int УлицаКод { get; set; }
        public int НомерДома { get; set; }
        public int КатегорияВозрастаКод { get; set; }
        public int КатегорияЗдоровьяКод { get; set; }
        public System.DateTime ДатаУстановленияУчета { get; set; } = DateTime.Now;
        public Nullable<System.DateTime> ДатаСнятияСУчета { get; set; } = DateTime.Now; 
        public Nullable<int> ЦветГлазКод { get; set; }
        public Nullable<int> ЦветВолосКод { get; set; }
        public Nullable<int> ТипЛичностиКод { get; set; }
        public Nullable<int> Рост { get; set; }
        public Nullable<int> Вес { get; set; }
    
        public virtual Возраст Возраст { get; set; }
        public virtual Город Город { get; set; }
        public virtual КатегорияВозраста КатегорияВозраста { get; set; }
        public virtual КатегорияЗдоровья КатегорияЗдоровья { get; set; }
        public virtual Пол Пол { get; set; }
        public virtual Регион Регион { get; set; }
        public virtual ТипЛичности ТипЛичности { get; set; }
        public virtual Улица Улица { get; set; }
        public virtual ЦветВолос ЦветВолос { get; set; }
        public virtual ЦветГлаз ЦветГлаз { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявления> Заявления { get; set; }

        public string FI => Фамилия + " " + Имя;
        public string FIO => Фамилия + " " + Имя + " " + Отчество;
        public string Address => Регион.Имя + ", " + Город.Имя + ", " + Улица.Имя + ", " + НомерДома;
    }
}
