//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VikaDiplom
{
    using System;
    using System.Collections.Generic;
    
    public partial class Опекуны
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Опекуны()
        {
            this.Заявления = new HashSet<Заявления>();
        }
    
        public int Код { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public System.DateTime ДатаРождения { get; set; } = DateTime.Now;
        public decimal Телефон { get; set; }
        public int ЦельОбращенияКод { get; set; }
        public System.DateTime ДатаОбращения { get; set; } = DateTime.Now;
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявления> Заявления { get; set; }
        public virtual ЦельОбращения ЦельОбращения { get; set; }

        public string FIO => Фамилия + " " + Имя;
    }
}
